#!/usr/bin/groovy

def call(body) {
  def config = [:]
  body.resolveStrategy = Closure.DELEGATE_FIRST
  body.delegate = config
  body()

  def build = new com.westernasset.pipeline.operationRelease.opsRelease()

  lock("${params.prodEnv}") {
    build.build(
      params,
      "${params.gitScm}",
      "${params.gitBranchName}",
      "${params.gitCommit}",
      "${params.prodEnv}",
      "${params.drEnv}",
      "${params.crNumber}",
      "${params.liquibaseChangeLog}",
      "${params.liquibaseBuilderTag}",
      "${params.organizationName}",
      "${params.appGitRepoName}",
      "${params.releaseVersion}",
      "${params.buildNumber}",
      "${params.appDtrRepo}",
      "${params.projectType}",
      "${params.templates}",
      "${params.secrets}",
      "${params.imageTags}",
      "${params.startServerScripts}",
      "${params.stopServerScripts}",
      "${params.remoteAppUser}",
      "${params.secretsRemoteDests}",
      "${params.appArtifacts}",
      "${params.appArtifactsRemoteDests}",
      "${params.nonProdHostsMap}",
      "${params.prodHosts}",
      "${params.preInstallArtifacts}",
      "${params.preInstallArtifactsDests}",
      "${params.upstreamJobName}",
      "${params.upstreamBuildNumber}",
      "${params.appPath}",
      "${params.module}",
      "${params.fromEnv}",
      "${params.toEnv}",
      "${params.buildSteps}",
      "${params.preStartServerLocalCmds}",
      "${params.postStartServerLocalCmds}",
      "${params.builderTag}",
      "${params.jobIdsNonprod}",
      "${params.jobIdsProd}",
      "${params.deleteProdJobIds}",
      "${params.postDeploySteps}",
      "${params.postDeploySteps}",
      "${params.backupDest}",
      "${params.prodBucket}",
      "${params.S3KeyMap}",
      "${params.prodAccounts}",
      "${params.accountAppfileMap}",
      "${params.appfileStackMap}",
      "${params.dockerfileToTagMap}",
      "${params.templateFile}",
      "${params.stackName}",
      "${params.parametersOverridesMap}",
      "${params.tdsxFiles}",
      "${params.tdsxNames}",
      "${params.tdsxProjects}",
      "${params.twbFiles}",
      "${params.twbNames}",
      "${params.twbProjects}",
      "${params.tabbedFlag}",
      "${params.tdsxSecrets}",
      "${params.twbSecrets}",
      "${params.deleteNames}",
      "${params.deleteFromProjects}",
      "${params.verifyFromChange}",
      "${params.hostDomain}",
      "${params.os}",
      "${params.scriptRoot}",
      "${params.requesterId}",
      "${params.charts}",
      "${params.dockerfiles}",
      "${params.namespace}",
      "${params.helmRepos}",
      "${params.connectors}",
      "${params.parameterJsonString}"
    )
  }
}
